# Generated by Django 4.2.3 on 2023-08-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
