# Generated by Django 4.2.3 on 2023-08-23 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache_effectuer', models.CharField(max_length=70)),
                ('nom_equip', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QHSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_licence', models.CharField(max_length=70)),
                ('date_exp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panne', models.CharField(max_length=70)),
                ('ti', models.CharField(max_length=100)),
                ('ttr', models.CharField(max_length=100)),
                ('nbr_panne', models.CharField(max_length=70)),
                ('cumul_panne', models.CharField(max_length=100)),
                ('pourc_panne', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=70)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date_peremption',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panne', models.CharField(max_length=70)),
                ('ti', models.CharField(max_length=100)),
                ('ttr', models.CharField(max_length=100)),
                ('nbr_panne', models.CharField(max_length=70)),
                ('cumul_panne', models.CharField(max_length=100)),
                ('pourc_panne', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=70)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.maintenance')),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.membre')),
                ('qhse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.qhse')),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.total')),
            ],
        ),
    ]
