# Generated by Django 4.2.3 on 2023-09-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_maintenance_membre_qhse_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='qhse',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='total',
        ),
    ]
