# Generated by Django 4.2.3 on 2023-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_historique_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='cumul_panne',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='frequence',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='nbr_panne',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='pourc_panne',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='ti',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='ttr',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
