# Generated by Django 4.2.3 on 2023-09-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_total_remove_maintenance_nom_equip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='cumul_panne',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='pourc_panne',
        ),
    ]
