# Generated by Django 4.2.3 on 2023-09-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_historique_cumul_panne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='cumul_panne',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='pourc_panne',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
