# Generated by Django 4.2.3 on 2023-09-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_historique_cumul_panne_historique_pourc_panne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='cumul_panne',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='pourc_panne',
        ),
    ]
