# Generated by Django 4.2.3 on 2023-09-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_historique_cumul_panne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='frequence',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nbr_panne',
        ),
    ]
