# Generated by Django 4.2.3 on 2023-09-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_historique_frequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='type',
        ),
    ]
