# Generated by Django 4.2.3 on 2023-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_historique_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sécurité', 'Sécurité'), ('Entretien', 'Entretien'), ('Mouillage', 'Mouillage'), ('Electricité', 'Electricité'), ('Cordage Marine', 'Cordage Marine'), ('Navigation', 'Navigation')], max_length=50, null=True),
        ),
    ]
