# Generated by Django 4.2.3 on 2023-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_date_peremption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='panne',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
